Dev
Aulrata/Glossary pull request #2
Opened 2022-10-10 12:07 UTC by Aulrata

Stage 3 done!
Ready for a review

2022-11-27 16:41 UTC, luck-o-o-luck requested changes

2022-11-27 16:41 UTC, luck-o-o-luck commented on Glossary/Service.cs
> +                }
![image](https://user-images.githubusercontent.com/78821666/200123065-eba721b4-f0ab-416f-a861-f1019fd68ffb.png)
Всё было бы хорошо, если бы ты с самого начала задал какую-то валидацию. Человек, не знающий правила, может ввести рандомные циферки и получить результат, который я скинула выше.

2022-11-27 16:41 UTC, luck-o-o-luck commented on Glossary/Pixel.cs
> +    }
Почему выбор перешел к internal классу? 
Для конструктора нет валидации данных. То есть на самом деле у тебя пройдут отрицательные значения

2022-11-27 16:41 UTC, luck-o-o-luck commented on Glossary/Service.cs
> +                }
Ещё хотелось бы, чтобы ты явно давал ввести сначала ширину, а потом высоту. Подозреваю, что так легче избежать ошибки в пользовательском вводе

2022-11-27 16:41 UTC, luck-o-o-luck commented on Glossary/Service.cs
> +            }
А есть ли у тебя сейчас возможность начать игру заново, не завершая программу? А еще советую присмотреться к LINQ 
Как тебе идея разделить консольный ввод и сами алгоритмы на разные классы? Сейчас у тебя смешанная логика, что не очень хорошо

2022-11-27 16:41 UTC, luck-o-o-luck commented on Glossary/Space.cs
> +        public ConsoleColor Color { get; set; }
На самом деле internal класс - это не плохо. Но у тебя внутри есть публичные сеттеры, а это значит, что можно вложить null-значения, если у тебя нет в методах валидации

2022-11-29 09:36 UTC, Aulrata commented on Glossary/Pixel.cs
> +    }
Interanl класс, это не внимательность. Раньше когда создаешь новый класс он автоматически ставит public, а теперь internal и еще не привык изменять модификатор доступа. 
Валидации данных нет, т.к. там задаются значения, введенные пользователем. Я их обработал и теперь для конструктора не нужна валидация.

2022-11-29 09:38 UTC, Aulrata commented on Glossary/Service.cs
> +                }
Валидация и разделение ввода данных готово!

2023-12-06 14:33 UTC, closed without merging